sudo: required
services:
  - docker

before_install:
  - docker build -t bee25141/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bee25141/react-test npm test

after_success:
  - docker build -t bee25141/multi-client ./client
  - docker build -t bee25141/multi-nginx ./nginx
  - docker build -t bee25141/multi-server ./server
  - docker build -t bee25141/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push bee25141/multi-client
  - docker push bee25141/multi-nginx
  - docker push bee25141/multi-server
  - docker push bee25141/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: MultiDocker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-422728243729
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY